version: "3.9"

services:
  api:
    build: ./backend
    env_file: ./backend/.env
    expose:
      - "8000"
    networks:
      - webnet

  # Frontend em modo DEV (Vite)
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_BASE=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "5173"
    networks:
      - webnet

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
